# Generated by Django 4.2 on 2023-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_new_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='content',
            field=models.TextField(default='default content'),
        ),
    ]
