# Generated by Django 4.2 on 2023-04-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_new_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='slug',
        ),
    ]
