# Generated by Django 4.2 on 2023-04-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
